# Generated by Django 4.1.5 on 2023-01-31 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatComputerElems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa kategorii')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL kategorii')),
            ],
            options={
                'verbose_name': 'Kategoria dla elementów',
                'verbose_name_plural': 'Kategorie dla elementów',
            },
        ),
        migrations.CreateModel(
            name='ComputerElems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nagłówek')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Cały tekst')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Zdjęcie')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Czas tworzenia')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Czas aktualizacji')),
                ('available', models.BooleanField(default=True, verbose_name='Dostępny')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.catcomputerelems', verbose_name='Kategoria')),
            ],
            options={
                'verbose_name': 'Element komputera',
                'verbose_name_plural': 'Elementy komputera',
            },
        ),
    ]
