# Generated by Django 4.1.5 on 2023-01-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerelems',
            name='price',
            field=models.FloatField(default=100, null=True, verbose_name='Cena'),
        ),
    ]
